# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 1, 16, 50, 782322, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
