# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160404_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 22, 11, 37, 800513, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
