# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160407_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 21, 36, 32, 124981, tzinfo=utc), verbose_name=b'date published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 21, 36, 32, 124190, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
